name: ci

on:
  push:
    branches: ["main"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["main"]
  schedule:
    - cron: "27 21 * * 4"

jobs:
  ci:
    name: Run prettier scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ESLint
        run: npm install prettier@3.0.0

      - name: Run Prettier
        run: npx prettier src 
          --check
          --find-config-path .prettierrc.json
